/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from 'react'
import * as THREE from 'three'
import { useFrame } from '@react-three/fiber'
import { useGLTF, useTexture } from '@react-three/drei'
import { useLayoutEffect } from 'react'

const SCALE = 1

export default function Phone() {
  const group = useRef()
  const { scene, nodes, materials } = useGLTF('/models/smart_phone/scene.gltf')
  const texture = useTexture('/models/smart_phone/screen.png')

  useLayoutEffect(() => {
    scene.traverse(
      (obj) =>
        obj.type === 'Mesh' && (obj.receiveShadow = obj.castShadow = true)
    )
    Object.assign(materials.Screen, {
      roughness: 0.15,
      metalness: 1,
      emissive: new THREE.Color('#000'),
      envMapIntensity: 0.6,
    })
    materials['Screen'].map = texture
    materials['Screen'].needsUpdate = true
  }, [scene, nodes, materials])

  useFrame((state) => {
    const t = state.clock.getElapsedTime()
    group.current.rotation.x = THREE.MathUtils.lerp(
      group.current.rotation.x,
      Math.cos(t / 2) / 10 + 0.25,
      0.1
    )
    group.current.rotation.y = THREE.MathUtils.lerp(
      group.current.rotation.y,
      Math.sin(t / 4) / 25,
      0.1
    )
    group.current.rotation.z = THREE.MathUtils.lerp(
      group.current.rotation.z,
      Math.sin(t / 4) / 50,
      0.1
    )
    group.current.position.y = THREE.MathUtils.lerp(
      group.current.position.y,
      (-5 + Math.sin(t)) / 10,
      0.1
    )
  })

  return (
    <group ref={group} position={[0, 1, 0]}>
      <group rotation={[Math.PI / 8, 0, 0]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group
            rotation={[Math.PI / 2, 0, 0]}
            scale={[-1.05 / SCALE, -2.2 / SCALE, -0.09 / SCALE]}
          >
            <mesh
              geometry={nodes.Cube_Camera_0.geometry}
              material={materials.Camera}
            />
            <mesh
              geometry={nodes.Cube_Metallic_phone_0.geometry}
              material={materials.Metallic_phone}
            />
            <mesh
              geometry={nodes.Cube_Screen_0.geometry}
              material={materials.Screen}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/smart_phone/scene.gltf')
