name: Deploy to Github Pages on push to master

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [13.12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Contentful API key
        uses: TickX/var-to-dotenv@v1.1.1
        with:
          key: 'REACT_APP_CONTENTFUL_ACCESS_TOKEN'
          value: ${{secrets.CONTENTFUL_ACCESS_TOKEN}}
      - run: |
          npm install
          npm run build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.5.9
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
