name: Deploy to Github Pages on push to master

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.3.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          npm install
      - name: Add Contentful API key
        uses: TickX/var-to-dotenv@v1.1.4
        with:
          key: 'REACT_APP_CONTENTFUL_ACCESS_TOKEN'
          value: ${{secrets.CONTENTFUL_ACCESS_TOKEN}}
      - name: Add Contentful key WFH Privacy Policy
        uses: TickX/var-to-dotenv@v1.1.4
        with:
          key: 'REACT_APP_CONTENTFUL_WFH_PRIVACY_POLICY_ID'
          value: '72C8wbuNa19PpNOKGDOHG'
      - name: Add Contentful WFH Project Page
        uses: TickX/var-to-dotenv@v1.1.4
        with:
          key: 'REACT_APP_CONTENTFUL_WFH_PROJECT_ID'
          value: '7KTLMwpXTnYG9r2HHBUcjQ'
      - name: Add Contentful SFH Project page
        uses: TickX/var-to-dotenv@v1.1.4
        with:
          key: 'REACT_APP_CONTENTFUL_SFH_PROJECT_ID'
          value: 'sw3NKWxaSum0MDkyydCp4'
      - name: Add Contentful Appademin
        uses: TickX/var-to-dotenv@v1.1.4
        with:
          key: 'REACT_APP_CONTENTFUL_APPADEMIN_ID'
          value: '1e2oEtgX80ZRIyYdbacVkO'
      - name: Build
        run: |
          npm run build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
